# Generated by Django 5.0.4 on 2024-05-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_newuser_is_active_newuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'email', 'verbose_name_plural': 'emails'},
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
