# Generated by Django 5.0.4 on 2024-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_newuser_options_alter_newuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
